"use client";

/**
 * A table extracted from the source paper (data-table). Structured tables are
 * rendered from the document, not re-generated by the model (README diff A):
 *   - structure_kind "flat"    → markdown (parsed into a real <table>)
 *   - structure_kind "spanned" → server-provided HTML (rowspan/colspan kept)
 *
 * The actual rendering lives in the shared `TableBody` so the answer-flow table
 * and the evidence-panel copy stay identical. Wrapped in `overflow-x-auto` so
 * wide tables scroll in-place.
 */

import type { TableData } from "@/lib/types";
import { TableBody } from "./table-body";

export function StructuredTable({ table }: { table: TableData }) {
  return (
    <figure className="my-4 max-w-[560px] overflow-hidden rounded-lg border border-line bg-surface">
      <figcaption className="border-b border-line px-3 py-2 font-mono text-[0.7rem] font-medium uppercase tracking-wide text-ink-faint">
        {table.label}
        {table.caption ? (
          <span className="font-normal normal-case tracking-normal text-ink-soft">
            {" "}
            — {table.caption}
          </span>
        ) : null}
      </figcaption>
      <div className="overflow-x-auto">
        <TableBody table={table} />
      </div>
    </figure>
  );
}
