"""initial schema — 11 tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-29

Hand-written (NOT autogenerated) initial migration creating all 11 PaperLens
tables plus the partial unique indexes, the polling index, and the TEXT+CHECK
constraints. Constraint / index names are spelled literally to match the
``naming_convention`` in ``app/db/base.py`` so a later autogenerate produces an
empty diff.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Reusable dialect types.
UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB
TS = postgresql.TIMESTAMP(timezone=True)

# The one real DB enum. create_type=False so op.create_table does not emit a
# duplicate CREATE TYPE — we create/drop it explicitly below.
message_role = postgresql.ENUM(
    "user", "assistant", "system", name="message_role", create_type=False
)

# CHECK vocabularies (mirror app/db/models.py).
_STATUS = (
    "'uploaded', 'queued', 'processing', 'text_ready', "
    "'full_ready', 'rejected', 'failed', 'deleted'"
)
_STAGE = "'parsing', 'cropping', 'captioning', 'chunking', 'embedding', 'indexing'"
_CHUNK_TYPE = "'text', 'table_child', 'table_parent', 'fig_caption', 'figure'"
_VLM_STATUS = "'pending', 'done', 'failed'"
_STRUCTURE_KIND = "'flat', 'spanned'"
_LINK_TYPE = "'explicit_ref', 'caption', 'same_page'"


def upgrade() -> None:
    # Native enum type used by messages.role.
    message_role.create(op.get_bind(), checkfirst=True)

    # --- projects ---------------------------------------------------------- #
    op.create_table(
        "projects",
        sa.Column("id", UUID, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "settings",
            JSONB,
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_projects"),
    )

    # --- documents --------------------------------------------------------- #
    op.create_table(
        "documents",
        sa.Column("id", UUID, nullable=False),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'uploaded'"),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.SmallInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", TS, nullable=True),
        sa.Column(
            "ingest_generation",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "figure_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("deleted_at", TS, nullable=True),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_documents"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_documents_project_id_projects",
        ),
        sa.CheckConstraint(
            f"status IN ({_STATUS})", name="status_valid"
        ),
        sa.CheckConstraint(
            f"stage IS NULL OR stage IN ({_STAGE})", name="stage_valid"
        ),
        sa.CheckConstraint(
            "progress IS NULL OR (progress >= 0 AND progress <= 100)",
            name="progress_range",
        ),
    )
    # Partial unique index: one live document per (project, sha256).
    op.create_index(
        "uq_documents_project_id_file_sha256",
        "documents",
        ["project_id", "file_sha256"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # Partial polling index for pending / in-flight documents.
    op.create_index(
        "ix_documents_pending",
        "documents",
        ["status"],
        unique=False,
        postgresql_where=sa.text(
            "status IN ('uploaded', 'queued', 'processing') AND deleted_at IS NULL"
        ),
    )

    # --- figures ----------------------------------------------------------- #
    op.create_table(
        "figures",
        sa.Column("id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("vlm_summary", sa.Text(), nullable=True),
        sa.Column("image_path", sa.Text(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("bbox", JSONB, nullable=True),
        sa.Column(
            "vlm_status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_figures"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_figures_document_id_documents",
        ),
        sa.CheckConstraint(
            f"vlm_status IN ({_VLM_STATUS})", name="vlm_status_valid"
        ),
    )

    # --- tables ------------------------------------------------------------ #
    op.create_table(
        "tables",
        sa.Column("id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("html", sa.Text(), nullable=True),
        sa.Column("markdown_flat", sa.Text(), nullable=True),
        sa.Column(
            "structure_kind",
            sa.String(length=16),
            server_default=sa.text("'flat'"),
            nullable=False,
        ),
        sa.Column("n_rows", sa.Integer(), nullable=True),
        sa.Column("n_cols", sa.Integer(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("bbox", JSONB, nullable=True),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_tables"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_tables_document_id_documents",
        ),
        sa.CheckConstraint(
            f"structure_kind IN ({_STRUCTURE_KIND})",
            name="structure_kind_valid",
        ),
    )

    # --- chunks ------------------------------------------------------------ #
    op.create_table(
        "chunks",
        sa.Column("id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embed_text", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("section_path", sa.Text(), nullable=True),
        sa.Column("heading_levels", JSONB, nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("bbox", JSONB, nullable=True),
        sa.Column(
            "chunk_type",
            sa.String(length=16),
            server_default=sa.text("'text'"),
            nullable=False,
        ),
        sa.Column(
            "is_embedded",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_quarantined",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("figure_id", UUID, nullable=True),
        sa.Column("table_id", UUID, nullable=True),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_chunks"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_chunks_document_id_documents",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_chunks_project_id_projects"
        ),
        sa.ForeignKeyConstraint(
            ["figure_id"], ["figures.id"], name="fk_chunks_figure_id_figures"
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["tables.id"], name="fk_chunks_table_id_tables"
        ),
        sa.CheckConstraint(
            f"chunk_type IN ({_CHUNK_TYPE})", name="chunk_type_valid"
        ),
    )
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"], unique=False)
    op.create_index("ix_chunks_project_id", "chunks", ["project_id"], unique=False)

    # --- chunk_figures ----------------------------------------------------- #
    op.create_table(
        "chunk_figures",
        sa.Column("id", UUID, nullable=False),
        sa.Column("chunk_id", UUID, nullable=False),
        sa.Column("figure_id", UUID, nullable=False),
        sa.Column("link_type", sa.String(length=16), nullable=False),
        sa.Column(
            "confidence", sa.Float(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_chunk_figures"),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunks.id"], name="fk_chunk_figures_chunk_id_chunks"
        ),
        sa.ForeignKeyConstraint(
            ["figure_id"],
            ["figures.id"],
            name="fk_chunk_figures_figure_id_figures",
        ),
        sa.CheckConstraint(
            f"link_type IN ({_LINK_TYPE})", name="link_type_valid"
        ),
        sa.UniqueConstraint(
            "chunk_id", "figure_id", "link_type", name="chunk_figure_link"
        ),
    )

    # --- conversations ----------------------------------------------------- #
    op.create_table(
        "conversations",
        sa.Column("id", UUID, nullable=False),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("deleted_at", TS, nullable=True),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_conversations"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_conversations_project_id_projects",
        ),
    )

    # --- messages ---------------------------------------------------------- #
    op.create_table(
        "messages",
        sa.Column("id", UUID, nullable=False),
        sa.Column("conversation_id", UUID, nullable=False),
        sa.Column("role", message_role, nullable=False),
        sa.Column("parts", JSONB, nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_messages"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_messages_conversation_id_conversations",
        ),
    )

    # --- ingestion_jobs ---------------------------------------------------- #
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", UUID, nullable=False),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("attempt", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("failed_step", sa.String(length=64), nullable=True),
        sa.Column("step_timings_ms", JSONB, nullable=True),
        sa.Column("usage", JSONB, nullable=True),
        sa.Column("config_snapshot", JSONB, nullable=True),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ingestion_jobs"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_ingestion_jobs_document_id_documents",
        ),
    )

    # --- message_feedback -------------------------------------------------- #
    op.create_table(
        "message_feedback",
        sa.Column("id", UUID, nullable=False),
        sa.Column("message_id", UUID, nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "synced_to_langfuse",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_message_feedback"),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="fk_message_feedback_message_id_messages",
        ),
    )

    # --- collection_registry ----------------------------------------------- #
    op.create_table(
        "collection_registry",
        sa.Column("id", UUID, nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("dims", sa.Integer(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_collection_registry"),
    )
    # DB-enforced invariant: at most one active collection.
    op.create_index(
        "uq_collection_registry_active",
        "collection_registry",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )


def downgrade() -> None:
    # Reverse creation order (children before parents).
    op.drop_index("uq_collection_registry_active", table_name="collection_registry")
    op.drop_table("collection_registry")
    op.drop_table("message_feedback")
    op.drop_table("ingestion_jobs")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("chunk_figures")
    op.drop_index("ix_chunks_project_id", table_name="chunks")
    op.drop_index("ix_chunks_document_id", table_name="chunks")
    op.drop_table("chunks")
    op.drop_table("tables")
    op.drop_table("figures")
    op.drop_index("ix_documents_pending", table_name="documents")
    op.drop_index("uq_documents_project_id_file_sha256", table_name="documents")
    op.drop_table("documents")
    op.drop_table("projects")
    message_role.drop(op.get_bind(), checkfirst=True)
